// Code generated by ent, DO NOT EDIT.

package userpost

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the userpost type in the database.
	Label = "user_post"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldPostText holds the string denoting the post_text field in the database.
	FieldPostText = "post_text"
	// FieldPostImages holds the string denoting the post_images field in the database.
	FieldPostImages = "post_images"
	// FieldCreateTime holds the string denoting the create_time field in the database.
	FieldCreateTime = "create_time"
	// EdgeUserID holds the string denoting the user_id edge name in mutations.
	EdgeUserID = "user_id"
	// Table holds the table name of the userpost in the database.
	Table = "user_posts"
	// UserIDTable is the table that holds the user_id relation/edge.
	UserIDTable = "user_posts"
	// UserIDInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserIDInverseTable = "users"
	// UserIDColumn is the table column denoting the user_id relation/edge.
	UserIDColumn = "user_user_posts"
)

// Columns holds all SQL columns for userpost fields.
var Columns = []string{
	FieldID,
	FieldPostText,
	FieldPostImages,
	FieldCreateTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "user_posts"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_user_posts",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreateTime holds the default value on creation for the "create_time" field.
	DefaultCreateTime time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(int) error
)

// OrderOption defines the ordering options for the UserPost queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPostText orders the results by the post_text field.
func ByPostText(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPostText, opts...).ToFunc()
}

// ByCreateTime orders the results by the create_time field.
func ByCreateTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreateTime, opts...).ToFunc()
}

// ByUserIDField orders the results by user_id field.
func ByUserIDField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserIDStep(), sql.OrderByField(field, opts...))
	}
}
func newUserIDStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserIDInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserIDTable, UserIDColumn),
	)
}
