// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "User"},
		{Name: "password", Type: field.TypeString, Default: "Password"},
		{Name: "email", Type: field.TypeString, Default: "user@email.com"},
		{Name: "create_time", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// UserPostsColumns holds the columns for the "user_posts" table.
	UserPostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "post_text", Type: field.TypeString},
		{Name: "post_images", Type: field.TypeJSON},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "user_user_posts", Type: field.TypeInt, Nullable: true},
	}
	// UserPostsTable holds the schema information for the "user_posts" table.
	UserPostsTable = &schema.Table{
		Name:       "user_posts",
		Columns:    UserPostsColumns,
		PrimaryKey: []*schema.Column{UserPostsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "user_posts_users_userPosts",
				Columns:    []*schema.Column{UserPostsColumns[4]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		UsersTable,
		UserPostsTable,
	}
)

func init() {
	UserPostsTable.ForeignKeys[0].RefTable = UsersTable
}
